name = "SpeedyWeatherFTLE"
uuid = "b487dfcd-2a18-4dea-b622-756fb564dac9"
version = "1.0.0-DEV"
authors = ["Andrew Watford"]

[deps]
SpeedyWeather = "9e226e20-d153-4fed-8a5b-493def4f21a9"

[compat]
SpeedyWeather = "0.17.4"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
