name = "SpeedyWeatherFTLE"
uuid = "b487dfcd-2a18-4dea-b622-756fb564dac9"
version = "1.0.0-DEV"
authors = ["Andrew Watford"]

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
RingGrids = "d1845624-ad4f-453b-8ff4-a8db365bf3a7"
SpeedyWeather = "9e226e20-d153-4fed-8a5b-493def4f21a9"

[workspace]
projects = ["docs"]

[sources]
RingGrids = {rev = "mk/lyapunov", subdir = "RingGrids", url = "https://github.com/SpeedyWeather/SpeedyWeather.jl"}
SpeedyWeather = {rev = "mk/lyapunov", url = "https://github.com/SpeedyWeather/SpeedyWeather.jl"}

[compat]
Documenter = "1.16.1"
RingGrids = "0.1.1"
SpeedyWeather = "0.17.4"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
